#! /bin/bash

MYSQL_PROD="mysql --user=root --password=root radius --silent --skip-column-names -e"

MYSQL_DEV="mysql --user=root --password=root radius -e"

MYSQL=$MYSQL_DEV

# #     # ####### #       ######  ####### ######
# #     # #       #       #     # #       #     #
# #     # #       #       #     # #       #     #
# ####### #####   #       ######  #####   ######
# #     # #       #       #       #       #   #
# #     # #       #       #       #       #    #
# #     # ####### ####### #       ####### #     #
#

function password {
  # -a algorithm
  #        use algorithm for password generation.
  #        0 - (default) pronounceable password generation
  #        1 - random character password generation
  #
  # -n num_of_pass
  #        generate num_of_pass number of passwords. Default is 6.
  #
  # -m min_pass_len
  #        generate  password  with  minimum  length   min_pass_len.    If
  #        min_pass_len  >  max_pass_len then max_pass_len = min_pass_len.
  #        Default minimum password length is 8.
  #
  # -x max_pass_len
  #        generate  password  with  maximum  length   max_pass_len.    If
  #        min_pass_len  >  max_pass_len then max_pass_len = min_pass_len.
  #        Default maximum password length is 10.
  #
  # -M mode
  #        Use symbolsets specified with  mode  for  password  generation.
  #        mode  is  a text string consisting of characters S, s, N, n, C,
  #        c, L, l. Where:
  #
  #        L      generator must use small letters symbol  set  for  every
  #               generated  password  (always  present  if  pronounceable
  #               password generation algorithm is used).

  apg -a 1 -n 1 -m 8 -x 8 -M L
}


# Strong
F_STG='\033[0;31m' # Red
# Emphazie
F_EMP='\033[0;32m' # Green
# Comment
F_CMT='\033[0;33m' # Yellow
# Reset
F_RST='\033[0m'

function echo_question {
  echo -e "${F_STG}$*?${F_RST}"
}

function echo_value {

  if [ -n "$2" ]; then
    SUGGESTION=" [${F_CMT}$2${F_RST}]"
  fi

  echo -e -n "${F_EMP}$1${F_RST}$SUGGESTION: "
}


# #     #  #####  ####### ######
# #     # #     # #       #     #
# #     # #       #       #     #
# #     #  #####  #####   ######
# #     #       # #       #   #
# #     # #     # #       #    #
#  #####   #####  ####### #     #


function case_user {
  VALUE="$1"
  shift 1
  VALUES=$@

  case $VALUE in

    add)
      user_add $VALUES
    ;;

    show)
      user_show $VALUES
    ;;

    update)
      user_update $VALUES
    ;;

    delete)
      user_delete $VALUES
    ;;

    *)

    ;;

  esac
}

function user_add {
  GUEST="$1"

  echo_question "Do you want to create a new user"

  echo_value "username"

  read USERNAME

  PASSWORD=$(password)
  echo_value  "password" $PASSWORD
  read INPUT

  if [ -n "$INPUT" ]; then
    PASSWORD="$INPUT"
  fi

  $MYSQL "
    INSERT
      INTO radcheck (username,attribute,op,value)
      VALUES ('$USERNAME','Cleartext-Password',':=','$PASSWORD');
  "

  if [ "$GUEST" == "guest" ]; then

    $MYSQL "
      INSERT
        INTO radcheck (username,attribute,op,value)
        VALUES ('$USERNAME','Access-Period',':=','360');
    "

  fi

  echo "Following values have been written to the database:"

  $MYSQL "
    SELECT *
    FROM radcheck
    WHERE username = '$USERNAME'

  "
}

function user_show {
  $MYSQL "
    SELECT username, value as password
      FROM radcheck
      WHERE attribute = 'Cleartext-Password'
        AND username <> '';
  "
}

function user_update {

  $MYSQL "

  "
}

function user_delete {
  SHORTNAME="$1"

  if [ -z "$SHORTNAME" ]; then

    echo "Enter username!" >2&

    exit 1

  fi

  $MYSQL "
    DELETE
      FROM radcheck
      WHERE shortname = '$SHORTNAME';
  "
}

# #     #    #     #####
# ##    #   # #   #     #
# # #   #  #   #  #
# #  #  # #     #  #####
# #   # # #######       #
# #    ## #     # #     #
# #     # #     #  #####

function nas_add {
  #NASNAME="$1"
  #SHORTNAME="$2"
  #SECRET="$3"

  echo "Add a new NAS!"
  echo -n "shortname: "
  read SHORTNAME
  echo -n "ip address: "
  read NASNAME
  echo -n "secret: "
  read SECRET

  $MYSQL "
    INSERT
      INTO nas (nasname,shortname,secret)
      VALUES ('$NASNAME','$SHORTNAME','$SECRET');
  "
}

function nas_show {
  $MYSQL "
    SELECT shortname, secret, nasname AS ip
      FROM nas;
  "
}

function nas_delete {
  SHORTNAME="$1"

  if [ -z "$SHORTNAME" ]; then

    echo "Enter username!" >2&

    exit 1

  fi

  $MYSQL "
    DELETE
      FROM nas
      WHERE shortname = '$SHORTNAME';
  "
}

#  #####  #######    #    #######
# #     #    #      # #      #
# #          #     #   #     #
#  #####     #    #     #    #
#       #    #    #######    #
# #     #    #    #     #    #
#  #####     #    #     #    #

function stat_user_last {
  $MYSQL "
    SELECT username, authdate, nasip FROM radpostauth
    WHERE reply = 'Access-Accept'
      AND nasip <> ''
    ORDER BY authdate DESC
    LIMIT 10;
  "
}

function stat_user_count {
  LAST_DAY="AND UNIX_TIMESTAMP('2013-07-02 14:12:38') - UNIX_TIMESTAMP(authdate) < 86400"

  $MYSQL "
    SELECT username, COUNT(username) AS logincount
    FROM radpostauth
    WHERE reply = 'Access-Accept'
      AND nasip <> ''
    GROUP BY username
    ORDER BY logincount DESC;
  "
}

function stat_user_log {
  $MYSQL "
    SELECT *
    FROM radpostauth
    ORDER BY authdate DESC
    LIMIT 20;
  "
}

function stat_nas_count {
  $MYSQL "
    SELECT nas.shortname, COUNT(nas.id) AS logincount
    FROM nas
    LEFT JOIN radpostauth
    ON radpostauth.nasip = nas.nasname
    GROUP BY nas.id;
  "
}

function stat_db_table {
  TABLE="$1"

  if [ -z "$TABLE" ]; then

    echo "Select table!"

    $MYSQL "
      SHOW TABLES;
    "

    exit 1
  fi

  $MYSQL "
    SELECT *
    FROM $TABLE
    LIMIT 100;
  "
}

# ######  ######
# #     # #     #
# #     # #     #
# #     # ######
# #     # #     #
# #     # #     #
# ######  ######

# # #    #  ####  #####   ##   #      #
# # ##   # #        #    #  #  #      #
# # # #  #  ####    #   #    # #      #
# # #  # #      #   #   ###### #      #
# # #   ## #    #   #   #    # #      #
# # #    #  ####    #   #    # ###### ######

function db_install_schema {
  $MYSQL "

    #
    # Table structure for table 'radacct'
    #

    CREATE TABLE radacct (

      radacctid             bigint(21)              NOT NULL auto_increment,
      acctsessionid         varchar(64)             NOT NULL default '',
      acctuniqueid          varchar(32)             NOT NULL default '',
      username              varchar(64)             NOT NULL default '',
      groupname             varchar(64)             NOT NULL default '',
      realm                 varchar(64)             default '',
      nasipaddress          varchar(15)             NOT NULL default '',
      nasportid             varchar(15)             default NULL,
      nasporttype           varchar(32)             default NULL,
      acctstarttime         datetime                NULL default NULL,
      acctstoptime          datetime                NULL default NULL,
      acctsessiontime       int(12)                 default NULL,
      acctauthentic         varchar(32)             default NULL,
      connectinfo_start     varchar(50)             default NULL,
      connectinfo_stop      varchar(50)             default NULL,
      acctinputoctets       bigint(20)              default NULL,
      acctoutputoctets      bigint(20)              default NULL,
      calledstationid       varchar(50)             NOT NULL default '',
      callingstationid      varchar(50)             NOT NULL default '',
      acctterminatecause    varchar(32)             NOT NULL default '',
      servicetype           varchar(32)             default NULL,
      framedprotocol        varchar(32)             default NULL,
      framedipaddress       varchar(15)             NOT NULL default '',
      acctstartdelay        int(12)                 default NULL,
      acctstopdelay         int(12)                 default NULL,
      xascendsessionsvrkey  varchar(10)             default NULL,

      PRIMARY KEY (radacctid),
      KEY username (username),
      KEY framedipaddress (framedipaddress),
      KEY acctsessionid (acctsessionid),
      KEY acctsessiontime (acctsessiontime),
      KEY acctuniqueid (acctuniqueid),
      KEY acctstarttime (acctstarttime),
      KEY acctstoptime (acctstoptime),
      KEY nasipaddress (nasipaddress)

    );

    #
    # Table structure for table 'radcheck'
    #

    CREATE TABLE radcheck (

      id                    int(11)                 unsigned NOT NULL auto_increment,
      username              varchar(64)             NOT NULL default '',
      attribute             varchar(64)             NOT NULL default '',
      op                    char(2)                 NOT NULL DEFAULT '==',
      value                 varchar(253)            NOT NULL default '',

      PRIMARY KEY (id),
      KEY username (username(32))

    );

    #
    # Table structure for table 'radgroupcheck'
    #

    CREATE TABLE radgroupcheck (

      id                    int(11)                 unsigned NOT NULL auto_increment,
      groupname             varchar(64)             NOT NULL default '',
      attribute             varchar(64)             NOT NULL default '',
      op                    char(2)                 NOT NULL DEFAULT '==',
      value                 varchar(253)            NOT NULL default '',

      PRIMARY KEY  (id),
      KEY groupname (groupname(32))

    );

    #
    # Table structure for table 'radgroupreply'
    #

    CREATE TABLE radgroupreply (

      id                    int(11)                 unsigned NOT NULL auto_increment,
      groupname             varchar(64)             NOT NULL default '',
      attribute             varchar(64)             NOT NULL default '',
      op                    char(2)                 NOT NULL DEFAULT '=',
      value                 varchar(253)            NOT NULL default '',

      PRIMARY KEY  (id),
      KEY groupname (groupname(32))

    );

    #
    # Table structure for table 'radreply'
    #

    CREATE TABLE radreply (

      id                    int(11)                 unsigned NOT NULL auto_increment,
      username              varchar(64)             NOT NULL default '',
      attribute             varchar(64)             NOT NULL default '',
      op                    char(2)                 NOT NULL DEFAULT '=',
      value                 varchar(253)            NOT NULL default '',

      PRIMARY KEY (id),
      KEY username (username(32))

    );


    #
    # Table structure for table 'radusergroup'
    #

    CREATE TABLE radusergroup (

      username              varchar(64)             NOT NULL default '',
      groupname             varchar(64)             NOT NULL default '',
      priority              int(11)                 NOT NULL default '1',

      KEY username (username(32))
    ) ;

    #
    # Table structure for table 'radpostauth'
    #

    CREATE TABLE radpostauth (

      id                    int(11)                 NOT NULL auto_increment,
      username              varchar(64)             NOT NULL default '',
      pass                  varchar(64)             NOT NULL default '',
      nasip                 varchar(64)             NOT NULL default '',
      reply                 varchar(32)             NOT NULL default '',
      authdate              timestamp               NOT NULL,

      PRIMARY KEY (id)

    );

  "
}

function db_install_nas {
  $MYSQL "

    #
    # Table structure for table 'nas'
    #

    CREATE TABLE nas (

      id                    int(10)                 NOT NULL auto_increment,
      nasname               varchar(128)            NOT NULL,
      shortname             varchar(32),
      type                  varchar(30)             DEFAULT 'other',
      ports                 int(5),
      secret                varchar(60)             DEFAULT 'secret' NOT NULL,
      server                varchar(64),
      community             varchar(50),
      description           varchar(200)            DEFAULT 'RADIUS Client',

      PRIMARY KEY (id),
      KEY nasname (nasname)

    );

  "
}

function db_install_cui {
  $MYSQL "

    #
    # Table structure for table 'cui'
    #

    CREATE TABLE cui (

      clientipaddress       varchar(15)             NOT NULL default '',
      callingstationid      varchar(50)             NOT NULL default '',
      username              varchar(64)             NOT NULL default '',
      cui                   varchar(32)             NOT NULL default '',
      creationdate          timestamp               NOT NULL default CURRENT_TIMESTAMP,
      lastaccounting        timestamp               NOT NULL default '0000-00-00 00:00:00',

      PRIMARY KEY  (username,clientipaddress,callingstationid)

    ) ENGINE=MyISAM DEFAULT CHARSET=latin1;
  "
}

function db_install_ippool {
  $MYSQL "

    #
    # Table structure for table 'radippool'
    #

    CREATE TABLE radippool (

      id                    int(11)                 unsigned NOT NULL auto_increment,
      pool_name             varchar(30)             NOT NULL,
      framedipaddress       varchar(15)             NOT NULL default '',
      nasipaddress          varchar(15)             NOT NULL default '',
      calledstationid       VARCHAR(30)             NOT NULL,
      callingstationid      VARCHAR(30)             NOT NULL,
      expiry_time           DATETIME                NULL default NULL,
      username              varchar(64)             NOT NULL default '',
      pool_key              varchar(30)             NOT NULL,

      PRIMARY KEY (id),
      KEY radippool_poolname_expire (pool_name, expiry_time),
      KEY framedipaddress (framedipaddress),
      KEY radippool_nasip_poolkey_ipaddress (nasipaddress, pool_key, framedipaddress)

    ) ENGINE=InnoDB;
  "
}

function db_install_wimax {
  $MYSQL "

    #
    # WiMAX Table structure for table 'wimax',
    # which replaces the 'radpostauth' table.
    #

    CREATE TABLE wimax (

      id                    int(11)                 NOT NULL auto_increment,
      username              varchar(64)             NOT NULL default '',
      authdate              timestamp               NOT NULL,
      spi                   varchar(16)             NOT NULL default '',
      mipkey                varchar(400)            NOT NULL default '',
      lifetime              int(12)                 default NULL,

      PRIMARY KEY  (id),
      KEY username (username),
      KEY spi (spi)

    );
  "
}

# #    # #    # # #    #  ####  #####   ##   #      #
# #    # ##   # # ##   # #        #    #  #  #      #
# #    # # #  # # # #  #  ####    #   #    # #      #
# #    # #  # # # #  # #      #   #   ###### #      #
# #    # #   ## # #   ## #    #   #   #    # #      #
#  ####  #    # # #    #  ####    #   #    # ###### ######

function db_uninstall_schema {
  $MYSQL "
    DROP TABLE IF EXISTS
      radacct,
      radcheck,
      radgroupcheck,
      radgroupreply,
      radreply,
      radusergroup,
      radpostauth;
  "
}

function db_uninstall_nas {
  $MYSQL "
    DROP TABLE IF EXISTS
      nas;
  "
}

function db_uninstall_cui {
  $MYSQL "
    DROP TABLE IF EXISTS
      cui;
  "
}

function db_uninstall_ippool {
  $MYSQL "
    DROP TABLE IF EXISTS
      radippool;
  "
}

function db_uninstall_wimax {
  $MYSQL "
    DROP TABLE IF EXISTS
      wimax;
  "
}

#  #####     #     #####  #######    ####### #     # #     #  #####  ####### ### ####### #     #  #####
# #     #   # #   #     # #          #       #     # ##    # #     #    #     #  #     # ##    # #     #
# #        #   #  #       #          #       #     # # #   # #          #     #  #     # # #   # #
# #       #     #  #####  #####      #####   #     # #  #  # #          #     #  #     # #  #  #  #####
# #       #######       # #          #       #     # #   # # #          #     #  #     # #   # #       #
# #     # #     # #     # #          #       #     # #    ## #     #    #     #  #     # #    ## #     #
#  #####  #     #  #####  #######    #        #####  #     #  #####     #    ### ####### #     #  #####

function case_db {
  VALUE="$1"
  shift 1
  VALUES="$*"

  case $VALUE in
    install)
      case_db_install $VALUES
    ;;

    uninstall)
      case_db_install $VALUES
    ;;

  esac
}

function case_db_install {

  case "$1" in
    schema)
      db_install_schema
    ;;

    nas)
      db_install_nas
    ;;

    cui)
      db_install_cui
    ;;

    ippool)
      db_install_ippool
    ;;

    wimax)
      db_install_wimax
    ;;

    all)
      db_install_schema
      db_install_nas
      db_install_cui
      db_install_ippool
      db_install_wimax
    ;;

    *)
      db_install_schema
    ;;

  esac

}

function case_db_uninstall {
  case "$1" in

    schema)
      db_uninstall_schema
    ;;

    nas)
      db_uninstall_nas
    ;;

    cui)
      db_uninstall_cui
    ;;

    ippool)
      db_uninstall_ippool
    ;;

    wimax)
      db_uninstall_wimax
    ;;

    all)
      db_uninstall_schema
      db_uninstall_nas
      db_uninstall_cui
      db_uninstall_ippool
      db_uninstall_wimax
    ;;

    *)
      db_uninstall_schema
    ;;

  esac
}

#  #####     #     #####  #######
# #     #   # #   #     # #
# #        #   #  #       #
# #       #     #  #####  #####
# #       #######       # #
# #     # #     # #     # #
#  #####  #     #  #####  #######

case "$1" in



  user)
    shift 1
    case_user $@
    ;;

  nas)
    case "$2" in
      add)
        nas_add "$3" "$4" "$5"
      ;;

      delete)
        nas_delete "$3"
      ;;

      show)
        nas_show
      ;;
    esac
    ;;

  stat)

    case "$2" in
      db)
        stat_db_table $4
      ;;

      user)

      case "$3" in
        last)
          stat_user_last
        ;;

        count)
          stat_user_count
        ;;

        log)
          stat_user_log
        ;;

      esac
      ;;

      nas)

      case "$3" in
        count)
          stat_nas_count
        ;;

      esac
      ;;

    esac
    ;;

    db)
      shift 1
      case_db "$*"
    ;;

  *)

    help
    ;;

esac



