#! /bin/bash

. /etc/freeradius-bash-admin.conf

_usage() {
  echo "Usage: radius-import <dump-file.sql.gz>

-> Import a MySQL dump file.  
"
}

FILE="$1"

if [ -z "$FILE" ]; then
  _usage
  exit 1
fi

_prompt_yes "Import dump file? All data will be lost!"

_mysql_base " 
  DROP DATABASE IF EXISTS $MYSQL_DATABASE;
  CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE;
"

gunzip -c $FILE | mysql --user=$MYSQL_USER --password=$MYSQL_PASSWORD $MYSQL_DATABASE

# vim: set ts=2 sw=2 sts=2 et :
