#! /bin/bash

. /etc/freeradius-bash-admin.conf

_add() {

  SUM=50
  START=100
  END=$((START + SUM))

  for i in $(seq $START $END); do
    echo $i

    local USERNAME="g$i"
    local PASSWORD=$(password weak)

    _mysql "
      INSERT
        INTO radcheck (username,attribute,op,value)
        VALUES ('$USERNAME','Cleartext-Password',':=','$PASSWORD');
      INSERT
        INTO user (username,firstname,lastname)
        VALUES ('$USERNAME','Gast-Zugang','Nr. $i');
      INSERT
        INTO radusergroup (username,groupname,priority)
        VALUES ('$USERNAME','guests',1);
    "

  done

}

_show_expired() {
  _mysql "
    SELECT pa.username
    FROM radpostauth AS pa
    JOIN radcheck AS c
      ON pa.username = c.username
    WHERE c.attribute = 'Access-Period' 
      AND UNIX_TIMESTAMP() - UNIX_TIMESTAMP(pa.authdate) > c.value
    GROUP BY pa.username
    ORDER BY pa.authdate DESC
    ;
  "
}

_delete_expired() {

   local TMP='/tmp/freeradius-bash-admin_guests.tmp'

  _show_expired > $TMP 

  for GUEST in $(cat $TMP); do
    _mysql "DELETE FROM radcheck WHERE username = '$GUEST';"
    echo "Delete '$GUEST'."
  done
}

_help() {
  echo "Usage: $0 <options>

Options:

  - add
  - show-expired
  - delete-expired
"
}

case "$1" in

  add)
    shift 1
    _add $@
    ;;

  show-expired)
    _show_expired
    ;;

  delete-expired)
    _delete_expired
    ;;

  *)
    _help
    ;;

esac

# vim: set ts=2 sw=2 sts=2 et :