#! /bin/bash

. /etc/freeradius-bash-admin.conf

MYSQL="mysql --user=$MYSQL_USER --password=$MYSQL_PASSWORD $MYSQL_DATABASE -e"

_add() {
  GUEST="$1"

  echo_question "Do you want to create a new user"

  echo_value "username"

  read USERNAME

  PASSWORD=$(password)
  echo_value  "password" $PASSWORD
  read INPUT

  if [ -n "$INPUT" ]; then
    PASSWORD="$INPUT"
  fi

  $MYSQL "
    INSERT
      INTO radcheck (username,attribute,op,value)
      VALUES ('$USERNAME','Cleartext-Password',':=','$PASSWORD');
  "

  if [ "$GUEST" == "guest" ]; then

    $MYSQL "
      INSERT
        INTO radcheck (username,attribute,op,value)
        VALUES ('$USERNAME','Access-Period',':=','60');
    "

  fi

  echo "Following values have been written to the database:"

  $MYSQL "
    SELECT *
    FROM radcheck
    WHERE username = '$USERNAME'

  "
}

_show() {
  USERNAME="$1"

  if [ -z $USERNAME ]; then
    echo "Usage: show <username>"
    exit 1
  fi

  $MYSQL "
    SELECT *
      FROM radcheck
      WHERE username = '$USERNAME';
  "
}

_show_all() {
  $MYSQL "
    SELECT username, value as password
      FROM radcheck
      WHERE attribute = 'Cleartext-Password'
        AND username <> '';
  "
}

_update() {

  $MYSQL "

  "
}

_password() {
  USERNAME="$1"
  PASSWORD="$2"

  if [ -z "$USERNAME" ] || [ -z "$PASSWORD" ]; then
     echo "password <username> <password>"
     exit 1
  fi

  $MYSQL "UPDATE radcheck
    SET value = '$PASSWORD'
    WHERE username = '$USERNAME'
      AND attribute = 'Cleartext-Password'
  "
}

_delete() {
  local USERNAME="$1"

  if [ -z "$USERNAME" ]; then

    echo "Enter username!"

    exit 1
  fi

  $MYSQL "
    DELETE u, rug, rc
      FROM user AS u
      JOIN radusergroup AS rug
        ON u.username = rug.username
      JOIN radcheck as rc
        ON u.username = rc.username
      WHERE u.username = '$USERNAME';
  "
}

function _help {
  echo "Usage: $0 <command> [<args>]

The commands are:
  add              Add user
  show <username>                : Show user
  show-all                       : Show all user
  update           Update user
  password <username> <password> : Update password.
  delete <username>              : Delete user
  help                           : Display help topics
"
}

case "$1" in

  add)
    shift 1
    _add $@
    ;;

  show)
    shift 1
    _show $@
    ;;

  show-all)
    _show_all
  ;;

  update)
    shift 1
    _update $@
    ;;
  
  password)
    shift 1
    _password $@
    ;;

  delete)
    shift 1
    _delete $@
    ;;

  *)
    _help
    ;;

esac
