#! /bin/bash

. /etc/freeradius-bash-admin.conf

MYSQL="mysql --user=$MYSQL_USER --password=$MYSQL_PASSWORD $MYSQL_DATABASE -e"

_radpostauth() {
  $MYSQL "
    DELETE FROM radpostauth
    WHERE authdate < NOW() - INTERVAL 3 MONTH
    ORDER BY authdate DESC
  ;
  "
}

_help() {
  echo "Usage: $0 <options>

Options:
  - radpostauth
 "
}

case "$1" in

  radpostauth)
    _radpostauth
    ;;

  *)
    _help
    ;;

esac

# vim: set ts=2 sw=2 sts=2 et :