#! /bin/bash

. /etc/freeradius-bash-admin.conf


_value() {
  local DATABASE="$1"
  local COLUMN="$2"

  _mysql_silent "
    SELECT
      $COLUMN
      FROM $DATABASE
      WHERE username = '$USER_NAME';
  "
}

_add() {
  _prompt USER_NAME "User name"
  _prompt FIRST_NAME "First name"
  _prompt LAST_NAME "Last name"
  _prompt DESCRIPTION "Description"
  _prompt PASS_WORD "Password" $(_password_generator)

  if [ -z $USER_NAME ] && [ -z $PASS_WORD ]; then
    echo "User name and password can not be blank!"
    exit 1
  fi

  _mysql "
    INSERT
      INTO radcheck (username, attribute, op, value)
      VALUES ('$USER_NAME','Cleartext-Password',':=','$PASS_WORD');

    INSERT
      INTO user (username, firstname, lastname, description)
      VALUES ('$USER_NAME','$FIRST_NAME','$LAST_NAME','$DESCRIPTION');
  "

  echo "Those values have been written to the database:"

  _show "$USER_NAME"
}

_show() {
  USER_NAME="$1"

  if [ -z $USER_NAME ]; then
    echo "Usage: radius-user show <username> or <all>"
    exit 1
  fi

  if [ "$USER_NAME" = 'all' ]; then
    AND="AND r.username <> ''"
  else
    AND="AND r.username = '$USER_NAME'"
  fi

  _mysql "
    SELECT

      r.username AS Username,
      r.value AS Password,
      u.firstname as Firstname,
      u.lastname as Lastname,
      u.description as Description

      FROM radcheck AS r
      JOIN user AS u
        ON r.username = u.username
      WHERE r.attribute = 'Cleartext-Password'
        $AND
     ;
  "
}

_update() {

  USER_NAME="$1"

  if [ -z "$USER_NAME" ] ; then
     echo "Usage: radius-user update <username>"
     exit 1
  fi

  _prompt FIRST_NAME "First name" "$(_value 'user' 'firstname')"
  _prompt LAST_NAME "Last name" "$(_value 'user' 'lastname')"
  _prompt DESCRIPTION "Description" "$(_value 'user' 'description')"
  _prompt PASS_WORD "Password" "$(_password_generator)"

  _mysql "
    UPDATE radcheck
      SET
        value = '$PASS_WORD'
      WHERE username = '$USER_NAME'
        AND attribute = 'Cleartext-Password';

    UPDATE user
      SET
        firstname = '$FIRST_NAME',
        lastname = '$LAST_NAME',
        description = '$DESCRIPTION'
      WHERE username = '$USER_NAME';
  "

  _show "$USER_NAME"
}

_password() {
  USER_NAME="$1"

  if [ -z "$USER_NAME" ] ; then
     echo "Usage: radius-user password <username>"
     exit 1
  fi

  _prompt PASS_WORD "Enter password" $(_password_generator)

  _mysql "UPDATE radcheck
    SET value = '$PASS_WORD'
    WHERE username = '$USER_NAME'
      AND attribute = 'Cleartext-Password'
  "

  _show "$USER_NAME"
}

_delete() {
  local USER_NAME="$1"

  if [ -z "$USER_NAME" ]; then
    echo "Usage: radius-user delete <username>"
    exit 1
  fi

  _mysql "DELETE FROM user WHERE username = '$USER_NAME';"
  _mysql "DELETE FROM radcheck WHERE username = '$USER_NAME';"
  _mysql "DELETE FROM radusergroup WHERE username = '$USER_NAME';"
}

_usage() {
  echo "Usage: radius-user <options>

Options:

  add                            : Add user.
  show <username> or <all>       : Show user.
  update <username>              : Update user.
  password <username>            : Update password.
  delete <username>              : Delete user.
  help                           : Display help topics.
"
}

case "$1" in

  add)
    shift 1
    _add $@
    ;;

  show)
    shift 1
    _show $@
    ;;

  update)
    shift 1
    _update $@
    ;;

  password)
    shift 1
    _password $@
    ;;

  delete)
    shift 1
    _delete $@
    ;;

  *)
    _usage
    ;;

esac

# vim: set ts=2 sw=2 sts=2 et :