#! /bin/bash

. /etc/freeradius-bash-admin.conf

_value() {
  local COLUMN="$1"

  _mysql_silent "
    SELECT
      $COLUMN
      FROM nas
      WHERE shortname = '$SHORT_NAME';
  "
}

_add() {
  _prompt SHORT_NAME "Short name"
  _prompt SECRET "Secret" $(_password_generator)
  _prompt IP "IP address"
  _prompt DESCRIPTION "Description"
  
  _mysql "
    INSERT
      INTO nas (nasname, shortname, secret, description)
      VALUES ('$IP','$SHORT_NAME','$SECRET', '$DESCRIPTION');
  "
}

_show() {
  local SHORT_NAME="$1"

  if [ -z $SHORT_NAME ]; then
    echo "Usage: radius-nas show <shortname> or <all>"
    exit 1
  fi

  if [ "$SHORT_NAME" != 'all' ]; then
    local WHERE="WHERE shortname = '$SHORT_NAME'"    
  fi

  _mysql "
    SELECT 

      shortname as Shortname, 
      secret AS Secret, 
      nasname AS 'IP address',
      description AS Description

      FROM nas
      $WHERE
      ;
  "
}

_update() {
  local SHORT_NAME="$1"

  if [ -z "$SHORT_NAME" ] ; then
     echo "Usage: radius-nas update <shortname>"
     exit 1
  fi
  _prompt SHORT_NAME_UPDATE "Short name" "$(_value shortname)"
  _prompt SECRET "Secret" "$(_value secret)"
  _prompt IP "IP address" "$(_value nasname)"
  _prompt DESCRIPTION "Description" "$(_value description)"

  _mysql "
    UPDATE nas
      SET 
        nasname = '$IP',
        shortname = '$SHORT_NAME_UPDATE',
        secret = '$SECRET',
        description = '$DESCRIPTION'
      WHERE shortname = '$SHORT_NAME';
  "

  _show "$SHORT_NAME_UPDATE"
}

_delete() {
  local SHORT_NAME="$1"

  if [ -z "$SHORT_NAME" ]; then
    echo "Usage: radius-nas delete <shortname>"
    exit 1
  fi

  _prompt_yes "Delete nas (shortname: '$SHORT_NAME')?"

  _mysql "
    DELETE
      FROM nas
      WHERE shortname = '$SHORT_NAME';
  "
}

_usage() {
  echo "Usage: radius-nas <options>

-> Manage the network access server (Access points).

Options:

  add                       : Add a NAS.
  show <shortname> or <all> : Show a NAS.
  update <shortname>        : Update a NAS.
  delete <shortname>        : Delete a NAS by shortname.
  help                      : Show this help topic.
"
}

case "$1" in

  add)
    shift 1
    _add $@
    ;;

  show)
    shift 1
    _show $@
    ;;

  update)
    shift 1
    _update $@
    ;;

  delete)
    shift 1
    _delete $@
    ;;

  help)
    _usage
    ;;

  *)
    _usage
    ;;

esac

# vim: set ts=2 sw=2 sts=2 et :
