#! /bin/bash

. /etc/freeradius-bash-admin.conf

_value() {
  local COLUMN="$1"

  _mysql_silent "
    SELECT
      $COLUMN
      FROM infogroup
      WHERE groupname = '$GROUP_NAME';
  "
}

_add() {
  _prompt GROUP_NAME 'Group name'
  _prompt TITLE 'Title'
  _prompt DESCRIPTION 'Description'

  _mysql "
    INSERT
      INTO infogroup 
        (groupname, title, description)
      VALUES 
        ('$GROUP_NAME', '$TITLE', '$DESCRIPTION');
  "

  _show "$GROUP_NAME"
}

_show() {
  local GROUP_NAME="$1"

  if [ -z $GROUP_NAME ]; then
    echo "Usage: radius-group show <groupname> or <all>"
    exit 1
  fi

  if [ "$GROUP_NAME" != 'all' ]; then
    local WHERE="WHERE groupname ='$GROUP_NAME'"
  fi

  _mysql "
    SELECT 
      groupname as 'Group name',
      title as Title,
      description as Description
      FROM infogroup
      $WHERE;
  "
}

_prepopulate() {
  _mysql "
    INSERT INTO infogroup
      (groupname, title)
    VALUES
      ('guests45min', 'Gast-Zugang für 45 Minuten.'),
      ('guests90min', 'Gast-Zugang für 90 Minuten.'),
      ('guests9hours', 'Gast-Zugang für 9 Stunden.');
  "

  _mysql "
    INSERT INTO radgroupcheck
      (groupname, attribute, op, value)
    VALUES
      ('guests45min', 'Access-Period', ':=', 2700),
      ('guests90min', 'Access-Period', ':=', 5400),
      ('guests9hours', 'Access-Period', ':=', 32400);
  "

  _mysql "
    INSERT INTO radgroupreply
      (groupname, attribute, op, value)
    VALUES
      ('guests45min', 'Reply-Message', ':=', 'Gast-Zugang für 45 Minuten.'),
      ('guests90min', 'Reply-Message', ':=', 'Gast-Zugang für 90 Minuten.'),
      ('guests9hours', 'Reply-Message', ':=', 'Gast-Zugang für 9 Stunden.');
  "
}

_update() {
  local GROUP_NAME="$1"

  if [ -z "$GROUP_NAME" ] ; then
     echo "Usage: radius-group update <groupname>"
     exit 1
  fi

  _prompt TITLE 'Titel der Gruppe' "$(_value 'title')"
  _prompt DESCRIPTION 'Beschreibung der Gruppe' "$(_value 'description')"

  _mysql "
    UPDATE infogroup
      SET
        title = '$TITLE',
        description = '$DESCRIPTION'
      WHERE groupname = '$GROUP_NAME';
  "

  _show "$GROUP_NAME"
}

_delete() {
  local GROUP_NAME="$1"

  if [ -z "$GROUP_NAME" ]; then
    echo "Usage: radius-group delete <groupname>"
    exit 1
  fi

  _prompt_yes "Delete group '$GROUP_NAME'?"

  _mysql "DELETE FROM infogroup WHERE groupname = '$GROUP_NAME';"
}

_usage() {
  echo "Usage: radius-group <option>

-> Manage the groups.

Options:

  add                        : Add a group.
  prepopulate                : Prepopulate the group table.
  show <groupname> or <all>  : Show a specific group or all groups.
  update <groupname>         : Update a group.
  delete <groupname>         : Delete a group.
  help                       : Show this help message.
"
}

case "$1" in

  add)
    shift 1
    _add $@
    ;;

  show)
    shift 1
    _show $@
    ;;

  prepopulate)
    _prepopulate
    ;;

  update)
    shift 1
    _update $@
    ;;

  delete)
    shift 1
    _delete $@
    ;;

  help)
    _usage
    ;;

  *)
    _usage
    ;;

esac

# vim: set ts=2 sw=2 sts=2 et :
