#! /bin/bash

. /etc/freeradius-bash-admin.conf

_add {

  _prompt "TITLE" "Titel der Gruppe"
  _prompt "GROUPNAME" "Kurzname der Gruppe"
  _prompt "DESCRIPTION" "Beschreibung der Gruppe"

  _mysql "
    INSERT
      INTO groups (groupname,title,description)
      VALUES ('$GROUPNAME','$TITLE','$DESCRIPTION');
  "

  _mysql "
    SELECT *
      FROM groups
      WHERE groupname = '$GROUPNAME';
  "
}

# vim: set ts=2 sw=2 sts=2 et :
