#! /bin/bash

. /etc/freeradius-bash-admin.conf

MYSQL="mysql --user=$MYSQL_USER --password=$MYSQL_PASSWORD"

_usage() {
  echo "$0 <dump-file.sql.gz>"
}

FILE="$1"

if [ -z "$FILE" ]; then
  _usage
  exit 1
fi

$MYSQL -e " 
  DROP DATABASE IF EXISTS $MYSQL_DATABASE;
  CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE;
"

gunzip -c $FILE | mysql --user=$MYSQL_USER --password=$MYSQL_PASSWORD $MYSQL_DATABASE
