#! /bin/bash

. /etc/freeradius-bash-admin.conf

_add() {

  _prompt USER_NAME "User name"
  _prompt FIRST_NAME "First name"
  _prompt LAST_NAME "Last name"
  _prompt DESCRIPTION "Description"
  _prompt PASSWORD "Password" $(_password_generator)

  _mysql "
    INSERT
      INTO radcheck (username,attribute,op,value)
      VALUES ('$USER_NAME','Cleartext-Password',':=','$PASSWORD');
  "

  echo "Following values have been written to the database:"

  _mysql "
    SELECT *
    FROM radcheck
    WHERE username = '$USER_NAME'

  "
}

_show() {
  USERNAME="$1"

  if [ -z $USERNAME ]; then
    echo "Usage: $0 show <username> or <all>"
    exit 1
  fi
  
  if [ "$USERNAME" = 'all' ]; then
    AND="AND r.username <> ''"
  else
    AND="AND r.username = '$USERNAME'"
  fi

  $MYSQL "
    SELECT 

      r.username AS Username, 
      u.prename as Prename, 
      u.lastname as Lastname, 
      r.value AS Password
      
      FROM radcheck AS r
      JOIN user AS u 
        ON r.username = u.User_Name
      WHERE r.attribute = 'Cleartext-Password'
        $AND
     ;
  "
}

_update() {

  $MYSQL "

  "
}

_password() {
  USERNAME="$1"
  PASSWORD="$2"

  if [ -z "$USERNAME" ] || [ -z "$PASSWORD" ]; then
     echo "password <username> <password>"
     exit 1
  fi

  $MYSQL "UPDATE radcheck
    SET value = '$PASSWORD'
    WHERE username = '$USERNAME'
      AND attribute = 'Cleartext-Password'
  "
}

_delete() {
  local USERNAME="$1"

  if [ -z "$USERNAME" ]; then
    echo "Usage: delete <username>"
    exit 1
  fi
  
  $MYSQL "DELETE FROM user WHERE User_Name = '$USERNAME';"
  $MYSQL "DELETE FROM radcheck WHERE username = '$USERNAME';"
  $MYSQL "DELETE FROM radusergroup WHERE username = '$USERNAME';"
}

_help() {
  echo "Usage: $0 <command> [<args>]

The commands are:
  add              Add user
  show <username> or <all>       : Show user
  update           Update user
  password <username> <password> : Update password.
  delete <username>              : Delete user
  help                           : Display help topics
"
}

case "$1" in

  add)
    shift 1
    _add $@
    ;;

  show)
    shift 1
    _show $@
    ;;

  update)
    shift 1
    _update $@
    ;;
  
  password)
    shift 1
    _password $@
    ;;

  delete)
    shift 1
    _delete $@
    ;;

  *)
    _help
    ;;

esac

# vim: set ts=2 sw=2 sts=2 et :