#! /bin/bash

. /etc/freeradius-bash-admin.conf

_usage() {
  echo "Usage: radius-uninstall <table>

Tables:

  all    (user, nas, groups, radacct, radcheck, radgroupcheck, radgroupreply,
          radreply, radusergroup, radpostauth, cui, ippool, wimax)
  common (user, nas, groups, radacct, radcheck, radgroupcheck, radgroupreply,
          radreply, radusergroup, radpostauth)
  user
  groups
  nas
  radacct
  radcheck
  radgroupcheck
  radgroupreply
  radreply
  radusergroup
  radpostauth
  cui
  ippool
  wimax"
}

case "$1" in
  all)
    TABLES="user, groups, nas, radacct, radcheck, radgroupcheck, radgroupreply, radreply, radusergroup, radpostauth, cui, radippool, wimax"
  ;;

  common)
    TABLES="user, groups, nas, radacct, radcheck, radgroupcheck, radgroupreply, radreply, radusergroup, radpostauth"
  ;;

  user)
    TABLES="user"
  ;;

  groups)
    TABLES="groups"
  ;;

  nas)
    TABLES="nas"
  ;;

  radacct)
    TABLES="radacct"
  ;;

  radcheck)
    TABLES="radcheck"
  ;;

  radgroupcheck)
    TABLES="radgroupcheck"
  ;;

  radgroupreply)
    TABLES="radgroupreply"
  ;;

  radreply)
    TABLES="radreply"
  ;;

  radusergroup)
    TABLES="radusergroup"
  ;;

  radpostauth)
    TABLES="radpostauth"
  ;;

  cui)
    TABLES="cui"
  ;;

  ippool)
    TABLES="radippool"
  ;;

  wimax)
    TABLES="wimax"
  ;;

  *)
    _usage
  ;;

esac

_prompt_yes "Uninstall tables? All data will be lost!"

if [ -n "$TABLES" ]; then

  _mysql "
    DROP TABLE IF EXISTS
     $TABLES;
  "

fi

# vim: set ts=2 sw=2 sts=2 et :