#! /bin/bash

. /etc/freeradius-bash-admin.conf

_radpostauth() {
  _mysql "
    DELETE FROM radpostauth
    WHERE authdate < NOW() - INTERVAL 3 MONTH
    ORDER BY authdate DESC
  ;
  "
}

_usage() {
  echo "Usage: $0 <options>

Options:
  - radpostauth
 "
}

case "$1" in

  radpostauth)
    _radpostauth
    ;;

  *)
    _usage
    ;;

esac

# vim: set ts=2 sw=2 sts=2 et :