#! /bin/bash

. /etc/freeradius-bash-admin.conf

_check_id() {
  ID="$1"

  if [ -z "$ID" ]; then
    echo "Usage: $0 delete <id>

Select NAS by id!
"
    _show
    exit 1
  fi
}

_set_values() {
  while true ; do
    case "$1" in
      -n|--name)
        NAME="$2"
        shift 2
      ;;

      -p|--password|--pass)
        PASSWORD="$2"
        shift 2
      ;;

      -i|--ip)
        IP="$2"
        shift 2
      ;;

      *)
        break
      ;;
    esac
  done 
}

_add() {
  _mysql "
    INSERT
      INTO nas (nasname,shortname,secret)
      VALUES ('$NASNAME','$SHORTNAME','$SECRET');
  "
}

_show() {
  _mysql "
    SELECT id, shortname, secret, nasname AS ip
      FROM nas;
  "
}

_update() {
  _check_id "$1"

  shift

  _set_values "$@"

  echo $NAME
  echo $PASSWORD
  echo $IP

  _mysql "
    UPDATE nas
      SET nasname = 'lol',
      shortname = 'lol'
      WHERE id = '$ID';
  "
}

_delete() {
  ID="$1"

  if [ -z "$ID" ]; then
    echo "Usage: $0 delete <id>

Select NAS by id!
"
    _show
    exit 1
  fi

  _mysql "
    DELETE
      FROM nas
      WHERE id = '$ID';
  "

}

_help() {
  echo "Usage: $0 <command> [<args>]

The commands are:
   add              Add nas
   show             Show nas
   update           Update nas
   delete <id>      Delete nas by ID.
   help             Display help topics.
"
}

case "$1" in

  add)
    shift 1
    _add $@
    ;;

  show)
    shift 1
    _show $@
    ;;

  update)
    shift 1
    _update $@
    ;;

  delete)
    shift 1
    _delete $@
    ;;

  help)
    _help
    ;;

  *)
    _help
    ;;

esac

# vim: set ts=2 sw=2 sts=2 et :