#! /bin/bash

. /etc/freeradius-bash-admin.conf

MYSQL="mysql --user=$MYSQL_USER --password=$MYSQL_PASSWORD $MYSQL_DATABASE -e"

_user_last() {
  $MYSQL "
    SELECT username, authdate, nasip FROM radpostauth
    WHERE reply = 'Access-Accept'
      AND nasip <> ''
    ORDER BY authdate DESC
    LIMIT 100;
  "
}

_user_count() {

  INTERVAL="$@"

  if [ -z "$INTERVAL" ] ; then
    INTERVAL="1 WEEK"
  fi

  echo "Interval: $INTERVAL"

  $MYSQL "
    SELECT 
      CONCAT_WS(' ', u.prename, u.lastname) as Name,
      r.username AS Username, 
      COUNT(r.username) AS Count
    FROM radpostauth AS r
    JOIN user AS u
      ON u.User_Name = r.username
    WHERE r.reply = 'Access-Accept'
      AND r.nasip <> ''
      AND r.authdate > CURDATE() - INTERVAL $INTERVAL
    GROUP BY r.username
    ORDER BY Count DESC;
  "
}

_user_log() {
  $MYSQL "
    SELECT *
    FROM radpostauth
    ORDER BY authdate DESC
    LIMIT 500;
  "
}

_nas_count() {
  $MYSQL "
    SELECT nas.shortname, COUNT(nas.id) AS logincount
    FROM nas
    LEFT JOIN radpostauth
    ON radpostauth.nasip = nas.nasname
    GROUP BY nas.id;
  "
}

_db_values() {
  TABLE="$1"

  if [ -z "$TABLE" ]; then
    echo "Select table!"
    $MYSQL "SHOW TABLES;"
    exit 1
  fi

  $MYSQL "
    SELECT *
    FROM $TABLE
    LIMIT 500;
  "
}

_db_layout() {
  TABLE="$1"

  if [ -z "$TABLE" ]; then
    echo "Select table!"
    $MYSQL "SHOW TABLES;"
    exit 1
  fi

  $MYSQL "DESCRIBE $TABLE;"
}

_log_file() {
  tail -n 100 -f /var/log/freeradius/radius.log
}

_help() {
  echo "Usage: $0 <options>

Options:
  - user-last
  - user-count <interval> e.g.: \"1 week\" or \"2 month\"
  - user-log
  - nas-count
  - db-values <table>
  - db-layout <table>
  - log-file
"
}

case $1 in

  user-last)
    _user_last
  ;;

  user-count)
    shift
    _user_count "$@"
  ;;

  user-log)
    _user_log
  ;;

  nas-count)
    _nas_count
  ;;

  db-values)
    _db_values "$2"
  ;;

  db-layout)
    _db_layout "$2"
  ;;

  log-file)
    _log_file
  ;;

  *)
    _help
  ;;

esac

