#! /bin/bash

. /etc/freeradius-bash-admin.conf

#
# Table structure for table 'user'
#
_infouser() {
  _mysql "

    CREATE TABLE infouser (

      id                    int(10)                 NOT NULL auto_increment,
      username              varchar(64)             NOT NULL UNIQUE default '',
      firstename            varchar(128)            NOT NULL default '',
      lastname              varchar(128)            NOT NULL default '',
      description           varchar(200)            NOT NULL default '',

      PRIMARY KEY (id),
      KEY username_key (username)

    );

  "
}

#
# Table structure for table 'groups'
#
_infogroup() {
  _mysql "

    CREATE TABLE infogroup (

      id                    int(10)                 NOT NULL auto_increment,
      groupname             varchar(64)             NOT NULL UNIQUE default '',
      title                 varchar(128)            NOT NULL default '',
      description           varchar(200)            NOT NULL default '',

      PRIMARY KEY (id),
      KEY groupname_key (groupname)

    );

  "
}

#
# Table structure for table 'nas'
#
_nas() {
  _mysql "

    CREATE TABLE nas (

      id                    int(10)                 NOT NULL auto_increment,
      nasname               varchar(128)            NOT NULL,
      shortname             varchar(32),
      type                  varchar(30)             DEFAULT 'other',
      ports                 int(5),
      secret                varchar(60)             DEFAULT 'secret' NOT NULL,
      server                varchar(64),
      community             varchar(50),
      description           varchar(200)            DEFAULT 'RADIUS Client',

      PRIMARY KEY (id),
      KEY nasname (nasname)

    );

  "
}


#
# Table structure for table 'radacct'
#
_radacct() {
  _mysql "

    CREATE TABLE radacct (

      radacctid             bigint(21)              NOT NULL auto_increment,
      acctsessionid         varchar(64)             NOT NULL default '',
      acctuniqueid          varchar(32)             NOT NULL default '',
      username              varchar(64)             NOT NULL default '',
      groupname             varchar(64)             NOT NULL default '',
      realm                 varchar(64)             default '',
      nasipaddress          varchar(15)             NOT NULL default '',
      nasportid             varchar(15)             default NULL,
      nasporttype           varchar(32)             default NULL,
      acctstarttime         datetime                NULL default NULL,
      acctstoptime          datetime                NULL default NULL,
      acctsessiontime       int(12)                 default NULL,
      acctauthentic         varchar(32)             default NULL,
      connectinfo_start     varchar(50)             default NULL,
      connectinfo_stop      varchar(50)             default NULL,
      acctinputoctets       bigint(20)              default NULL,
      acctoutputoctets      bigint(20)              default NULL,
      calledstationid       varchar(50)             NOT NULL default '',
      callingstationid      varchar(50)             NOT NULL default '',
      acctterminatecause    varchar(32)             NOT NULL default '',
      servicetype           varchar(32)             default NULL,
      framedprotocol        varchar(32)             default NULL,
      framedipaddress       varchar(15)             NOT NULL default '',
      acctstartdelay        int(12)                 default NULL,
      acctstopdelay         int(12)                 default NULL,
      xascendsessionsvrkey  varchar(10)             default NULL,

      PRIMARY KEY (radacctid),
      KEY username (username),
      KEY framedipaddress (framedipaddress),
      KEY acctsessionid (acctsessionid),
      KEY acctsessiontime (acctsessiontime),
      KEY acctuniqueid (acctuniqueid),
      KEY acctstarttime (acctstarttime),
      KEY acctstoptime (acctstoptime),
      KEY nasipaddress (nasipaddress)

    );
  "
}

#
# Table structure for table 'radcheck'
#
_radcheck() {
  _mysql "

    CREATE TABLE radcheck (

      id                    int(11)                 unsigned NOT NULL auto_increment,
      username              varchar(64)             NOT NULL default '',
      attribute             varchar(64)             NOT NULL default '',
      op                    char(2)                 NOT NULL DEFAULT '==',
      value                 varchar(253)            NOT NULL default '',

      PRIMARY KEY (id),
      KEY username (username(32))

    );
  "
}

#
# Table structure for table 'radgroupcheck'
#
_radgroupcheck() {
  _mysql "

    CREATE TABLE radgroupcheck (

      id                    int(11)                 unsigned NOT NULL auto_increment,
      groupname             varchar(64)             NOT NULL default '',
      attribute             varchar(64)             NOT NULL default '',
      op                    char(2)                 NOT NULL DEFAULT '==',
      value                 varchar(253)            NOT NULL default '',

      PRIMARY KEY  (id),
      KEY groupname (groupname(32))

    );
  "
}

#
# Table structure for table 'radgroupreply'
#
_radgroupreply() {
  _mysql "

    CREATE TABLE radgroupreply (

      id                    int(11)                 unsigned NOT NULL auto_increment,
      groupname             varchar(64)             NOT NULL default '',
      attribute             varchar(64)             NOT NULL default '',
      op                    char(2)                 NOT NULL DEFAULT '=',
      value                 varchar(253)            NOT NULL default '',

      PRIMARY KEY  (id),
      KEY groupname (groupname(32))

    );

  "
}

#
# Table structure for table 'radreply'
#
_radreply() {
  _mysql "

    CREATE TABLE radreply (

      id                    int(11)                 unsigned NOT NULL auto_increment,
      username              varchar(64)             NOT NULL default '',
      attribute             varchar(64)             NOT NULL default '',
      op                    char(2)                 NOT NULL DEFAULT '=',
      value                 varchar(253)            NOT NULL default '',

      PRIMARY KEY (id),
      KEY username (username(32))

    );

  "
}

#
# Table structure for table 'radusergroup'
#
_radusergroup() {
  _mysql "

    CREATE TABLE radusergroup (

      username              varchar(64)             NOT NULL default '',
      groupname             varchar(64)             NOT NULL default '',
      priority              int(11)                 NOT NULL default '1',

      KEY username (username(32))
    ) ;

  "
}

#
# Table structure for table 'radpostauth'
#
_radpostauth() {
  _mysql "

    CREATE TABLE radpostauth (

      id                    int(11)                 NOT NULL auto_increment,
      username              varchar(64)             NOT NULL default '',
      pass                  varchar(64)             NOT NULL default '',
      nasip                 varchar(64)             NOT NULL default '',
      reply                 varchar(32)             NOT NULL default '',
      authdate              timestamp               NOT NULL,

      PRIMARY KEY (id)

    );

  "
}

#
# Table structure for table 'cui'
#
_cui() {
  _mysql "

    CREATE TABLE cui (

      clientipaddress       varchar(15)             NOT NULL default '',
      callingstationid      varchar(50)             NOT NULL default '',
      username              varchar(64)             NOT NULL default '',
      cui                   varchar(32)             NOT NULL default '',
      creationdate          timestamp               NOT NULL default CURRENT_TIMESTAMP,
      lastaccounting        timestamp               NOT NULL default '0000-00-00 00:00:00',

      PRIMARY KEY  (username,clientipaddress,callingstationid)

    ) ENGINE=MyISAM DEFAULT CHARSET=latin1;
  "
}

#
# Table structure for table 'radippool'
#
_ippool() {
  _mysql "

    CREATE TABLE radippool (

      id                    int(11)                 unsigned NOT NULL auto_increment,
      pool_name             varchar(30)             NOT NULL,
      framedipaddress       varchar(15)             NOT NULL default '',
      nasipaddress          varchar(15)             NOT NULL default '',
      calledstationid       VARCHAR(30)             NOT NULL,
      callingstationid      VARCHAR(30)             NOT NULL,
      expiry_time           DATETIME                NULL default NULL,
      username              varchar(64)             NOT NULL default '',
      pool_key              varchar(30)             NOT NULL,

      PRIMARY KEY (id),
      KEY radippool_poolname_expire (pool_name, expiry_time),
      KEY framedipaddress (framedipaddress),
      KEY radippool_nasip_poolkey_ipaddress (nasipaddress, pool_key, framedipaddress)

    ) ENGINE=InnoDB;
  "
}

#
# WiMAX Table structure for table 'wimax',
# which replaces the 'radpostauth' table.
#
_wimax() {
  _mysql "

    CREATE TABLE wimax (

      id                    int(11)                 NOT NULL auto_increment,
      username              varchar(64)             NOT NULL default '',
      authdate              timestamp               NOT NULL,
      spi                   varchar(16)             NOT NULL default '',
      mipkey                varchar(400)            NOT NULL default '',
      lifetime              int(12)                 default NULL,

      PRIMARY KEY  (id),
      KEY username (username),
      KEY spi (spi)

    );
  "
}

_database() {
  _prompt_yes "Drop all existing tables? All data will be lost!"

  _mysql_base "
    DROP DATABASE IF EXISTS $MYSQL_DATABASE; 
    CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE;
  "
}

_usage() {
  echo "Usage: radius-install [-d] <table>

Options:

  -d : Drop all existing tables.

Tables:

  all    (infouser, infogroup, nas, radacct, radcheck, radgroupcheck, radgroupreply,
          radreply, radusergroup, radpostauth, cui, ippool, wimax)
  common (infouser, infogroup, nas, radacct, radcheck, radgroupcheck, radgroupreply,
          radreply, radusergroup, radpostauth)
  infouser
  infogroup
  nas
  radacct
  radcheck
  radgroupcheck
  radgroupreply
  radreply
  radusergroup
  radpostauth
  cui
  ippool
  wimax"
}

DELETE="$1"

if [ "$DELETE" = "-d" ]; then
  shift 1
  _database
fi

case "$1" in
  all)
    _infouser
    _infogroup
    _nas
    _radacct
    _radcheck
    _radgroupcheck
    _radgroupreply
    _radreply
    _radusergroup
    _radpostauth
    _cui
    _ippool
    _wimax
  ;;

  common)
    _infouser
    _infogroup
    _nas
    _radacct
    _radcheck
    _radgroupcheck
    _radgroupreply
    _radreply
    _radusergroup
    _radpostauth
  ;;

  infouser)
    _infouser
  ;;

  infogroup)
    _infogroup
  ;;

  nas)
    _nas
  ;;

  radacct)
    _radacct
  ;;

  radcheck)
    _radcheck
  ;;

  radgroupcheck)
    _radgroupcheck
  ;;

  radgroupreply)
    _radgroupreply
  ;;

  radreply)
    _radreply
  ;;

  radusergroup)
    _radusergroup
  ;;

  radpostauth)
    _radpostauth
  ;;

  cui)
    _cui
  ;;

  ippool)
    _ippool
  ;;

  wimax)
    _wimax
  ;;

  *)
    _usage
  ;;

esac

# vim: set ts=2 sw=2 sts=2 et :
